main/urls.py
from django.urls import path
from . import views
from django.views.decorators.cache import never_cache


urlpatterns = [
    path("", views.index, name="index"),
    path("edit/", views.edit_profile, name="edit_profile"),
    path("delete/", views.delete_profile, name="delete_profile"),
    path("comment/delete/<int:pk>/", views.delete_comment, name="delete_comment"),
    path("comment/edit/<int:pk>/", views.edit_comment, name="edit_comment"),
    path("post/delete/<str:identifier>/", views.delete_post, name="delete_post"),
    path("categories/", views.categories, name="categories"),
    path("categories/<slug:slug>/", views.category, name="category"),
    path("collections/", views.collections, name="collections"),
    path("collections/<slug:slug>/", views.collection, name="collection"),
    path("load_posts/", views.load_posts, name="load_posts"),
    path("register/", views.register, name="register"),
    path("login/", views.login, name="login"),
    path("login/reset_password/", views.resetPassword, name="reset_password"),
    path("logout/", views.logout, name="logout"),
    path(
        "verification/<str:uidb64>/<str:token>/",
        views.verification,
        name="verification",
    ),
    path(
        "login/set_password/<str:uidb64>/<str:token>/",
        views.setPassword,
        name="set_password",
    ),
    path("posts/add/", views.post_add, name="post_add"),
    path("post/<str:identifier>/", views.PostDetailView.as_view(), name="post_detail"),
    path("post/<str:identifier>/edit/", views.post_edit, name="post_edit"),
    # path("post/<str:identifier>/delete/", views.post_delete, name="post_delete"),
    path("post/<str:identifier>/bookmark/", views.post_bookmark, name="post_bookmark"),
    path("<str:username>/", never_cache(views.profile), name="profile"),
    path("follow/<str:username>/", views.follow, name="follow"),
    path("unfollow/<str:username>/", views.unfollow, name="unfollow"),
]

main/models.py
import os
import markdown
import random
from functools import partial

from PIL import Image
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.db import models
from django.conf.urls.static import static
from django.db.models import CharField
from django_resized import ResizedImageField
from django.utils.text import slugify
from django.core.validators import RegexValidator
from random_username.generate import generate_username
from mdeditor.fields import MDTextField
from tyf.settings import MEDIA_ROOT
from registry.models import Major, University
from utils.utils import generate_media_path, generate_uuid, generate_pastel_color
from tyf import settings
from mptt.models import MPTTModel, TreeForeignKey


validator_telegram = RegexValidator(
    regex=r"^(?:|(https?:\/\/)?(|www)[.]?((t|telegram)\.me)\/)[a-zA-Z0-9_]{5,32}$",
    message="Telegram profile link should be in the format of https://t.me/username or https://telegram.me/username",
)

validator_vkontakte = RegexValidator(
    regex=r"^(?:|(https?:\/\/)?(|www)[.]?(vk\.com)\/)[a-zA-Z0-9_]{3,32}$",
    message="VK profile link should be in the format of https://vk.com/username",
)

User = get_user_model()


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        unique=True,
        blank=False,
        null=True,
        related_name="profile",
    )
    email = models.EmailField(unique=False, blank=False, null=False)
    username = models.CharField(max_length=50, unique=True, blank=True, null=True)
    first_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=True, null=True)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    university = models.ForeignKey(
        University,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="University",
    )
    major = models.ForeignKey(
        Major,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name="Major",
    )
    date_of_birth = models.DateField(blank=True, null=True)
    date_joined = models.DateTimeField(blank=True, null=True)
    bio = models.TextField(blank=True, null=True)
    avatar = ResizedImageField(
        crop=["middle", "center"],
        size=[300, 300],
        force_format="WEBP",
        quality=100,
        upload_to=partial(generate_media_path, key="email", remove_with_same_key=True),
        blank=True,
        null=False,
        verbose_name="Avatar",
    )
    thumbnail = models.ImageField(
        upload_to=partial(generate_media_path, key="email", remove_with_same_key=True),
        blank=True,
        null=True,
        verbose_name="Thumbnail",
    )
    points = models.IntegerField(default=0, blank=True, null=True)
    awards = models.IntegerField(default=0, blank=True, null=True)
    telegram = models.URLField(
        blank=True, null=True, validators=[validator_telegram], verbose_name="Telegram"
    )
    vkontakte = models.URLField(
        blank=True, null=True, validators=[validator_vkontakte], verbose_name="VK"
    )
    __original_mode = None

    def save(
        self,
        *args,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
        **kwargs,
    ):
        if self.avatar != self.__original_mode:
            self.__original_mode = self.avatar
            # self.save_thumbnail()

        if not self.username:
            username = generate_username()[0]
            while Profile.objects.filter(username=username).exists():
                username = generate_username()[0]
            self.username = generate_username()[0]

        super(Profile, self).save(force_insert, force_update, *args, **kwargs)

    # def save_thumbnail(self):
    #     if not self.avatar:
    #         return
    #     image = Image.open(self.avatar)
    #     image.thumbnail((49, 50), Image.Resampling.LANCZOS)
    #     thumb_name, _ = os.path.splitext(self.avatar.name)
    #     thumb_filename = thumb_name + "_thumb" + ".webp"
    #     image.save(MEDIA_ROOT + thumb_filename, "WEBP")
    #     self.thumbnail = thumb_filename
    #     return True

    def is_following(self, profile):
        return self.following.filter(following_id=profile.id).exists()

    def is_followed(self, profile):
        return self.followers.filter(follower_id=profile.id).exists()

    @property
    def get_avatar(self):
        if self.avatar:
            return self.avatar.url
        return settings.DEFAULT_USER_AVATAR

    def __str__(self):
        return self.username

    @property
    def get_telegram(self):
        if self.telegram:
            return "@" + self.telegram.split("/")[-1]
        return None

    @property
    def get_vkontakte(self):
        if self.vkontakte:
            return self.vkontakte.split("/")[-1]
        return None


class Follow(models.Model):
    follower = models.ForeignKey(
        Profile, related_name="following", on_delete=models.CASCADE
    )
    following = models.ForeignKey(
        Profile, related_name="followers", on_delete=models.CASCADE
    )
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.follower} followed {self.following} at {self.created_at}"


class Category(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, unique=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(default="", max_length=50, blank=True, null=True)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Collection(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, unique=True)
    description = models.TextField(blank=True)
    slug = models.SlugField(default="", max_length=50, blank=True, null=True)

    def save(self, *args, **kwargs):
        value = self.name
        self.slug = slugify(value, allow_unicode=True)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, unique=True)
    color = models.CharField(
        max_length=10, primary_key=False, editable=False, blank=True, null=True
    )

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.name = '#' + self.name
        self.color = generate_pastel_color()
        super(Tag, self).save(*args, **kwargs)


class Media(models.Model):
    content_type = models.ForeignKey(
        ContentType, on_delete=models.CASCADE, related_name="media"
    )
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey("content_type", "object_id")
    original_filename = models.CharField(max_length=255, blank=True, null=True)
    file = models.FileField(
        upload_to=partial(
            generate_media_path, key="object_id", remove_with_same_key=False
        ),
        null=True,
        blank=True,
    )

    def save(self, *args, **kwargs):
        if not self.original_filename and self.file:
            self.original_filename = os.path.basename(self.file.name)
        super(Media, self).save(*args, **kwargs)

    def filename(self):
        return os.path.basename(self.file.name)

    description = models.CharField(max_length=255, blank=True, null=True)

    def filetype(self):
        return os.path.splitext(self.file.name)[1][1:]


class Comment(MPTTModel):
    identifier = CharField(max_length=8, primary_key=False, editable=False, unique=True)
    post = models.ForeignKey("Post", on_delete=models.CASCADE, related_name="comments")
    author = models.ForeignKey(
        Profile, on_delete=models.CASCADE, related_name="comments"
    )
    content = models.TextField()
    stars = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    parent = TreeForeignKey(
        "self", on_delete=models.CASCADE, null=True, blank=True, related_name="replies"
    )

    def save(
        self,
        *args,
        force_insert=False,
        force_update=False,
        using=None,
        update_fields=None,
        **kwargs,
    ):

        max_depth = 5
        if self.parent and self.parent.level >= max_depth - 1:
            self.parent = self.parent.parent
        self.identifier = generate_uuid(klass=Comment)
        super(Comment, self).save(force_insert, force_update, *args, **kwargs)


class Post(models.Model):
    active = models.BooleanField(default=True)
    media_files = GenericRelation(Media)
    comments = GenericRelation(Comment)
    identifier = CharField(max_length=8, primary_key=False, editable=False, unique=True)
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, related_name="posts"
    )
    collections = models.ManyToManyField(Collection, related_name="posts", blank=True)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name="posts")
    title = models.CharField(max_length=255)
    content = MDTextField()
    stars = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag, related_name="posts", blank=True)
    media = GenericRelation(
        to="Media",
        related_query_name="media",
        content_type_field="content_type",
        object_id_field="object_id",
    )

    def save(
        self,
        *args,
        force_insert=False,
        force_update=False,

main/forms.py
from django import forms
from django_select2 import forms as s2forms
from django.forms import modelformset_factory

from django.contrib.auth import get_user_model
from registry.models import Major, University
from .models import Post, Comment, Media, Profile
from django.contrib.contenttypes.admin import GenericStackedInline
from django.contrib.auth.forms import PasswordChangeForm as BasePasswordChangeForm


User = get_user_model()


class UniversityWidget(s2forms.ModelSelect2Widget):
    queryset = University.objects.all().order_by("name")
    is_required = False
    search_fields = [
        "name__icontains",
        "city__icontains",
        "country__icontains",
    ]


class MajorWidget(s2forms.ModelSelect2Widget):
    queryset = Major.objects.all().order_by("name")
    is_required = False
    search_fields = [
        "name__icontains",
    ]


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = "__all__"
        widgets = {
            "university": UniversityWidget,
            "major": MajorWidget,
        }


class MultipleFileInput(forms.ClearableFileInput):
    allow_multiple_selected = True


class MultipleFileField(forms.FileField):
    def __init__(self, *args, **kwargs):
        kwargs.setdefault("widget", MultipleFileInput())
        super().__init__(*args, **kwargs)

    def clean(self, data, initial=None):
        single_file_clean = super().clean
        if isinstance(data, (list, tuple)):
            result = [single_file_clean(d, initial) for d in data]
        else:
            result = single_file_clean(data, initial)
        return result


class PostForm(forms.ModelForm):
    media_files = MultipleFileField(required=False)
    tags = forms.CharField(max_length=255, required=False)

    class Meta:
        model = Post
        fields = [
            "title",
            "category",
            "tags",
            "content",
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["title"].widget.attrs.update(
            {
                "placeholder": "Title",
            }
        )

        self.fields["tags"].widget.attrs.update(
            {
                "placeholder": "math,science,etc",
            }
        )


class EditProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        required=False,
        widget=forms.DateInput(attrs={"class": "form-control", "type": "date"}),
    )

    avatar = forms.ImageField(
        required=False, widget=forms.FileInput(attrs={"class": "form-control-file"})
    )

    bio = forms.CharField(
        required=False,
        widget=forms.Textarea(attrs={"class": "form-control", "rows": 5}),
    )

    university = forms.ModelChoiceField(
        queryset=University.objects.all().order_by("name"),
        required=False,
    )

    major = forms.ModelChoiceField(
        queryset=Major.objects.all().order_by("name"),
        required=False,
    )

    autocomplete_fields = [
        "university",
        "major",
    ]

    class Meta:
        model = Profile
        fields = [
            "username",
            "first_name",
            "last_name",
            "middle_name",
            "university",
            "major",
            "date_of_birth",
            "bio",
            "avatar",
            "telegram",
            "vkontakte",
        ]
        widgets = {
            "university": UniversityWidget,
            "major": MajorWidget,
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["first_name"].widget.attrs.update(
            {
                "placeholder": "Ivan",
            }
        )

        self.fields["last_name"].widget.attrs.update(
            {
                "placeholder": "Ivanov",
            }
        )

        self.fields["middle_name"].widget.attrs.update(
            {
                "placeholder": "Ivanovich",
            }
        )

        self.fields["telegram"].widget.attrs.update(
            {
                "placeholder": "https://t.me/username",
            }
        )

        self.fields["vkontakte"].widget.attrs.update(
            {
                "placeholder": "https://vk.com/username",
            }
        )

        self.fields["bio"].widget.attrs.update(
            {
                "placeholder": "Tell your friends about yourself",
            }
        )


class CommentForm(forms.ModelForm):
    parent = forms.ModelChoiceField(
        queryset=Comment.objects.all(), widget=forms.HiddenInput, required=False
    )

    class Meta:
        model = Comment
        fields = (
            "content",
            "parent",
        )
        labels = {
            "content": "",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["content"].widget.attrs.update(
            {"class": "form-control comments__content", "placeholder": "Leave a comment"}
        )


class PasswordChangeForm(BasePasswordChangeForm):
    old_password = forms.CharField(
        label="Old password",
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "autofocus": True}
        ),
        required=False,
    )

    new_password1 = forms.CharField(
        label="New password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False,
    )

    new_password2 = forms.CharField(
        label="Confirm new password",
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
        required=False,
    )

    class Meta:
        model = User
        fields = ("old_password", "new_password1", "new_password2")

templates/main/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Tell Your Friends - Sign In</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link
        href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
        rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
            <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
    </svg>
    <div class="container-fluid position-relative d-flex p-0">
        <div id="spinner"
            class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem;
                            height: 3rem;
                            color: var(--primary) !important"
                     role="status">
                    <span class="sr-only">Loading...</span>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="flex row vh-100 align-items-center justify-content-center" style="min-height: 100vh">
                <div class="col-12 row col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    {% for msg in messages %}
                        {% if 'success' in msg.tags %}
                        <div class="alert alert-success d-flex align-items-center" role="alert" style="width: 100% !important; border-radius: 1rem !important;">
                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                            <div style="margin-left: 1rem !important;">
                                {{ msg }}
                            </div>
                        </div>
                        {% endif %}
                        {% if 'info' in msg.tags %}
                        <div class="alert alert-info d-flex align-items-center" role="alert" style="width: 100% !important; border-radius: 1rem !important;">
                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#info-fill"/></svg>
                            <div style="margin-left: 1rem !important;">
                                {{ msg }}
                            </div>
                        </div>
                        {% endif %}
                        {% if 'warning' in msg.tags %}
                        <div class="alert alert-warning d-flex align-items-center" role="alert" style="width: 100% !important; border-radius: 1rem !important;">
                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                            <div style="margin-left: 1rem !important;">
                                {{ msg }}
                            </div>
                        </div>
                        {% endif %}
                        {% if 'error' in msg.tags %}
                        <div class="alert alert-danger d-flex align-items-center" role="alert" style="width: 100% !important; border-radius: 1rem !important;">
                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                            <div style="margin-left: 1rem !important;">
                                {{ msg }}
                            </div>
                        </div>
                        {% endif %}
                    {% endfor %}

                    <div class="bg-secondary rounded p-4" style="border-radius: 1rem !important;">
                        <div class="text-center align-items-center justify-content-between mb-4">
                            <h3 class="fs-5">Sign In to <a href="{% url 'index' %}" class="fs-5" style="font-family: 'Roboto' !important;">Tell Your Friends</a></h3>
                        </div>
                        <div>
                            <a href="{% url 'social:begin' 'google-oauth2' %}" class="btn btn-dark border rounded-pill px-4 py-2 mb-2 w-100">
                                <img src="https://img.icons8.com/color/48/000000/google-logo.png" class="rounded float-start" width="24" height="24">
                                <span class="text-center" style="margin: 0% !important;">Continue with Google</span>
                            </a>
                            <a href="{% url 'social:begin' 'yandex-oauth2' %}" class="btn btn-dark border rounded-pill px-4 py-2 mb-2 w-100">
                                <img src="https://upload.wikimedia.org/wikipedia/commons/5/58/Yandex_icon.svg" class="rounded float-start" width="24" height="24">
                                <span class="text-center" style="margin: 0% !important;">Continue with Yandex</span>
                            </a>
                        </div>
                        <div class="col-md-12 mb-3">
                            <div class="login-or">
                                <hr class="hr-or">
                                <span class="span-or small">OR</span>
                            </div>
                        </div>
                        <form method="post" role="form">
                            {% csrf_token %}
                            <div class="form-floating mb-2" method="POST">
                                <input type="email" name="email" value="{{ email }}" class="form-control form-control-sm" style="border-radius: 1rem;" id="id_email" placeholder="name@example.com" required aria-invalid="true">
                                <label for="id_email">Email <label style="color: rgb(188, 28, 28);">*</label></label>
                            </div>
                            <div class="form-floating mb-3">
                                <input type="password" name="password" class="form-control form-control-sm" style="border-radius: 1rem;" id="id_password" placeholder="Password" required aria-invalid="true">
                                <label for="id_password">Password <label style="color: rgb(188, 28, 28);">*</label></label>
                            </div>
                            <div class="d-flex align-items-center justify-content-between mb-3">
                                <a href="{% url 'reset_password' %}">Forgot password?</a>
                            </div>
                            <button type="submit" class="btn btn-primary py-3 w-100 mb-4"
                                style="border-radius: 1rem !important">
                                <label style="color: var(--dark) !important;">Sign In</label>
                            </button>
                        </form>
                        <p class="text-center mb-0">
                            Don't have an Account? <a href="{% url 'register' %}">Sign Up</a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/main/set_password.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Tell Your Friends - Set Password</title>
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="" name="keywords">
    <meta content="" name="description">

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=JetBrains+Mono:ital,wght@0,100..800;1,100..800&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
    
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body>    
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
      <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
        <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
      </symbol>
    </svg>

    <div class="container-fluid position-relative d-flex p-0">
        <div id="spinner" class="show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
            <div class="spinner-border text-primary" style="width: 3rem; height: 3rem; color: var(--primary) !important;" role="status">
                <span class="sr-only">Loading...</span>
            </div>
        </div>

        <div class="container-fluid">
            <div class="flex row vh-100 align-items-center justify-content-center" style="min-height: 100vh;">   
                <div class="col-12 row col-sm-8 col-md-6 col-lg-5 col-xl-4">
                    {% for msg in messages %}
                        {% if 'error' in msg.tags %}
                            <div class="alert alert-danger d-flex align-items-center col-md-6" role="alert" style="width: 100% !important; border-radius: 1rem !important;">
                                <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Danger:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                                <div style="margin-left: 1rem !important;">
                                    {{ msg }}
                                </div>
                            </div>
                        {% endif %}
                    {% endfor %}
                    <div class="bg-secondary rounded p-4" style="border-radius: 1rem !important;">
                        <div class="text-center align-items-center justify-content-between mb-4">
                            <h3 class="fs-5">Enter new password</h3>
                        </div>
                        <form method="post" role="form">
                            {% csrf_token %}
                            <div class="form-floating mb-2">
                                <input type="password" name="new_password1" class="form-control form-control-sm" style="border-radius: 1rem;" id="id_new_password1" placeholder="Password" required aria-invalid="true">
                                <label for="id_new_password1">Password <label style="color: rgb(188, 28, 28);">*</label></label>
                            </div>
                            {{form.help_text}}
                            <div class="form-floating mb-4">
                                <input type="password" name="new_password2" class="form-control form-control-sm" style="border-radius: 1rem;" id="id_new_password2" placeholder="Password confirmation" required aria-invalid="true">
                                <label for="id_new_password2">Password confirmation <label style="color: rgb(188, 28, 28);">*</label></label>
                            </div>
                            {{form.label}}{{form.help_text|safe}}  
                            <button type="submit" class="btn btn-primary py-3 w-100 mb-2" style="border-radius: 1rem !important;"><label style="color: var(--dark) !important;">Submit</label></button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>

    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>